// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_mqtt();
Q_GHS_KEEP_REFERENCE(qml_register_types_mqtt)

class mqttPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    mqttPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_mqtt;
        Q_UNUSED(registration)
    }
};



#include "mqttplugin_mqttPlugin.moc"
